# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb7a605496f397f5de95153c0a7a2dfb6d471c7e2f95894abc96c641d3ba7e5fcd37dcbc3f102cccc45ff6691af45bc7c1209aba947f7ad7c104f2845303f275

test:
  secret_key_base: 0176e449b7bd8b19cdc5c08321e4267a06b0484e2f37054f4502f43e7daaba2a3a4f5dcf5bb3f6311ebcfb1c2918531e54a2d6deec36423a8087420bd2fa1326

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
